### ISSUE TITLE
[TODO] Support spectral data

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinydng#41]
Several ways to support spectral color...

- [x] Single channel TIFF files by encoding wavelength in its filename
 * `col_0500_nm.tiff`, `col_0550_nm.tiff`, `...`
 * No modification required to TIFF loader/writer
- [x] Multichannel TIFF file
  -  TinyDNG supports multichannel TIFF
  - Encode wavelength info to metatata tag? 
- [ ] SpectralTIFF: https://www.cg.tuwien.ac.at/research/rendering/spectralTIFF/index.html
- [ ] https://github.com/BeyondRGB/Imaging-Art-beyond-RGB/wiki/TIFF-Output-Images
